---

- name: create three VLANs
  hosts: arista

  tasks: 
  - name: create VLANs
    eos_vlan: name={{item.vlan_name}} vlanid={{item.vlan_id}}
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    with_items:
              - {vlan_name: hs1, vlan_id: 991}
              - {vlan_name: hs2, vlan_id: 992}
              - {vlan_name: hs3, vlan_id: 993}
