---

- name: cisco_file_transfer
  hosts: pynet-rtr1
  gather_facts: False

  tasks:
          - name: Transfer a small file to rtr1
            cisco_file_transfer:
                    source_file="/home/hsun/hsun_pynet_exercise/class6/test_file.txt"
                    dest_file=ex5_hsun_test_file.txt
                    overwrite=true
                    enable_scp=true
                    host={{ host }}
                    port={{ port }}
                    username={{ username }}
                    password={{ password }}
